// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7yfuWz8vu9kVPkDR67-NjUdxjOk_DPM',
    appId: '1:922728355854:web:7057fa63b7e70bc5ccc45f',
    messagingSenderId: '922728355854',
    projectId: 'airdash-4865f',
    authDomain: 'airdash-4865f.firebaseapp.com',
    storageBucket: 'airdash-4865f.firebasestorage.app',
    measurementId: 'G-NFVD3YC0Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjddAuT4VmofUlyn2V4CXwJGtjSJzDmkE',
    appId: '1:922728355854:android:4388632422828bb7ccc45f',
    messagingSenderId: '922728355854',
    projectId: 'airdash-4865f',
    storageBucket: 'airdash-4865f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfMUUfz03GWixGDiy2s5hvmI53a6tivTU',
    appId: '1:922728355854:ios:194c58f00b55bed2ccc45f',
    messagingSenderId: '922728355854',
    projectId: 'airdash-4865f',
    storageBucket: 'airdash-4865f.firebasestorage.app',
    iosBundleId: 'com.airdash.airdash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ7yfuWz8vu9kVPkDR67-NjUdxjOk_DPM',
    appId: '1:922728355854:web:772f6680bc56aa01ccc45f',
    messagingSenderId: '922728355854',
    projectId: 'airdash-4865f',
    authDomain: 'airdash-4865f.firebaseapp.com',
    storageBucket: 'airdash-4865f.firebasestorage.app',
    measurementId: 'G-LY7EHWPZYZ',
  );
}
